[package]
name = "FontLoom"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21"
rand = "0.8"
image = "0.24"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.16"
serde_json = "1.0"
colored = "2.0"
futures = "0.3.31"
headless_chrome = "1.0.15"
anyhow = "1.0"
